name: Automated Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # 允许写入代码内容
      pull-requests: write   # 允许创建和管理 Pull Requests

    steps:

      - name: Run Release Please
        uses: googleapis/release-please-action@v4 # https://github.com/googleapis/release-please-action
        with:
          release-type: "node"  # 这个可以是你的项目使用的配置文件对应的语言, 一般node使用的是package.json
          token: "${{ secrets.GH_TOKEN }}"  # 使用你的个人访问令牌
          target-branch: ${{ github.ref_name }}
          skip-github-release: true
