name: Automated Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # 允许写入代码内容
      pull-requests: write   # 允许创建和管理 Pull Requests

    steps:

      - name: Run Release Please
        uses: googleapis/release-please-action@v4 # https://github.com/googleapis/release-please-action
        with:
          release-type: "node"  # 这个可以是你的项目使用的配置文件对应的语言, 一般node使用的是package.json
          token: "${{ secrets.GH_TOKEN }}"  # 使用你的个人访问令牌
          target-branch: ${{ github.ref_name }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要

      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          cache: npm # 或 pnpm / yarn

      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: npm ci # 或 pnpm install / yarn install / bun install
        if: ${{ steps.release.outputs.release_created }}

      - name: Build with npm
        if: ${{ steps.release.outputs.release_created }}
        run: | # 或 pnpm build / yarn build / bun run build
          npm run build 
          cp dist/index.html dist/404.html

      # 打包成压缩文件
      - name: Archive build files
        if: ${{ steps.release.outputs.release_created }}
        run: zip -r build.zip ./dist  # 将 dist 文件夹打包成 build.zip

      # 创建新的发布
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if:  ${{ steps.release.outputs.release_created }} && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build.zip